Reserve Vault : Factory and Registry
tvl-labs/khalani-core pull request #199
Opened 2023-08-08 13:03 UTC by Defcon023

## Description 
Reserve vaults factory and registry

- Factory for deployment of vault for an asset, vault is deployed using deterministic cheap clones (minimal proxy EIP-1167)
- Registry which deploys new factory on its construction and takes the DEFAULT_ADMIN role of this factory, new vaults are deployed using registry so that a vault, it asset and other info can be registered on successful deployment

2023-08-10 12:53 UTC, samtvlabs commented on src/ReserveVault/Registry.sol
> +contract Registry is Ownable {
nit: Please add natspe + licensing

2023-08-11 13:28 UTC, Defcon023 commented on src/ReserveVault/Registry.sol
> +contract Registry is Ownable {
Added

2023-08-16 10:31 UTC, Defcon023 commented on src/ReserveVault/Registry.sol
> +        }
function signature has `allDeployedVaults` which means its a named return variable , so we don't need return statement explicitly

2023-08-16 10:39 UTC, Defcon023 commented on src/ReserveVault/Registry.sol
> +    function deployNewVault(
The registry deploys the factory on its creation and take the "VAULT_DEPLOYER_ROLE" in the vault factory, in this pattern the registry is meant to deploy the vaults that go into production and thus gets registered post deployment.

For experimental vault the EOA_ADMIN also takes VAULT_DEPLOYER_ROLE and can be used to deploy experimental vaults which don't go into the registry

Of course there can be other ways to do this :
1. Deployment Scripts should have 2 calls , first call to factory to deploy the contract and 2nd call to registry to register the address (in case of experimental vaults we will have to omit out this call)
2. Vault Factory makes a call to the Registry after it deploys the vault

Let me know

2023-08-16 10:45 UTC, samtvlabs commented on src/ReserveVault/Registry.sol
> +    function deployNewVault(
1 & 2 are patterns I am more familiar with. Do you have any samples of cases where this current pattern is used ?

2023-08-16 11:11 UTC, 0xsuryansh commented on src/ReserveVault/Registry.sol
> +        _vault = factory.deployNewVault(_asset, _name, _symbol, _roleManager, _profitMaxUnlockTime);
I have added validation in the factory

2023-08-16 11:16 UTC, 0xsuryansh commented on src/ReserveVault/VaultFactory.sol
> +contract VaultFactory is Context, AccessControlEnumerable {
added

2023-08-16 11:17 UTC, 0xsuryansh commented on src/ReserveVault/VaultFactory.sol
> +        }
thanks , added

2023-08-16 11:53 UTC, samtvlabs approved these changes

2023-08-16 11:54 UTC, samtvlabs requested changes
fix ci

2023-08-16 12:04 UTC, Defcon023 commented
> fix ci

Fixed.... fuzz test to test invalid called was being called by a valid caller in one of the fuzz runs

2023-08-16 13:03 UTC, samtvlabs approved these changes

2023-08-16 13:03 UTC, merged