temp upgrade scripts
tvl-labs/khalani-core pull request #212
Opened 2023-09-05 14:42 UTC by Defcon023

temporary scrripts

2023-09-05 15:17 UTC, serejke approved these changes

2023-09-19 13:48 UTC, Defcon023 commented on src/InterchainMessaging/gasPayment/InterchainGasPaymaster.sol
Added a todo in the contract

2023-09-19 13:50 UTC, Defcon023 commented on script/DeployKhalani.s.sol
> +        address hyperlaneIGP; //TODO, adjust after finalizing M2 Deployment
using IGP now

2023-09-19 14:33 UTC, samtvlabs requested changes

2023-09-19 14:33 UTC, samtvlabs commented on lib/hyperlane-monorepo/solidity/contracts/igps/InterchainGasPaymaster.sol
> +    // ==========a== Constants ============
@Defcon023 can you please fix this

2023-09-20 12:13 UTC, Defcon023 commented on lib/hyperlane-monorepo/solidity/contracts/igps/InterchainGasPaymaster.sol
> +    // ==========a== Constants ============
https://github.com/tvl-labs/khalani-core/pull/212/commits/6eb5131552c51c6348543a574fa6cea259fb70f8#diff-2a44663ba321cb67cdfa8696ec59cf75b18a95725d911049b6713a76491580e6R21

fixed it here, don't know why its showing old version

2023-09-20 13:43 UTC, samtvlabs commented on lib/hyperlane-monorepo/solidity/contracts/igps/InterchainGasPaymaster.sol
> +    // ==========a== Constants ============
strange. Thanks!

2023-09-20 13:46 UTC, samtvlabs approved these changes

2023-09-20 13:46 UTC, merged